version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - windows # disabled because of some linux specific code
      # - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  header: |
    ## Hi! 欢迎使用wlu-login-cli ({{ .Date }})

    The release only supports Linux.

  footer: |
    ## 感谢您的支持!

    以上就是在 {{ .Tag }} 上的改动!
  name_template: "{{.ProjectName}}-v{{.Version}}-Linux {{.Env.USER}}"


nfpms:
  - id: packages
    package_name: ""
    formats:
      - deb
      - rpm
    vendor: syx0310
    homepage: https://github.com/syx0310/wlu-login-cli
    maintainer: syx0310
    license: Apache 2.0
