version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  header: |
    ## Hi! 欢迎使用wlu-login-cli ({{ .Date }})

    first release

  footer: |
    ## 感谢您的支持!

    以上就是在 {{ .Tag }} 上的改动!
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"


nfpms:
  - id: packages
    package_name: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - deb
      - rpm
    vendor: syx0310
    homepage: https://github.com/syx0310/wlu-login-cli
    maintainer: syx0310
    license: Apache 2.0
